// world-parity.mjs — compare the pure-Node world (js/world.js) against the
// golden browser autopilot baseline at tests/golden/baseline-dish1.json
// (format: {version:"baseline-dish/1", cases:[{seed, brain, gens:[{gen,eggs,
// rivalEggs,survived,deathReason,decisions,logHash}]}]}).
//
// The baseline may not exist yet (generated by a separate process). In that
// case this harness SKIPs (exit 0) so CI stays green until it lands.
//
// Standalone: node tests/world-parity.mjs   (exit 1 on any mismatch)
// Wired in via tests/world-parity.test.ts for `npm test`.
import { readFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { runLineage, WORLD_VERSION } from "../js/world.js";

const FIELDS = ["gen", "eggs", "rivalEggs", "survived", "deathReason", "decisions", "logHash"];

export async function runParity() {
  const baselineUrl = new URL("./golden/baseline-dish1.json", import.meta.url);
  let raw;
  try {
    raw = readFileSync(baselineUrl, "utf8");
  } catch (e) {
    console.log("[world-parity] golden baseline not yet available (" + baselineUrl.pathname + ") — skipping.");
    return { skipped: true, passed: 0, failed: 0 };
  }

  const baseline = JSON.parse(raw);
  if (baseline.version && baseline.version !== "baseline-" + WORLD_VERSION) {
    console.warn(`[world-parity] note: baseline version ${JSON.stringify(baseline.version)} vs world ${JSON.stringify(WORLD_VERSION)}`);
  }
  const cases = Array.isArray(baseline.cases) ? baseline.cases : [];

  let passed = 0, failed = 0;
  const diffs = [];
  for (const c of cases) {
    const gens = Array.isArray(c.gens) ? c.gens : [];
    const n = Math.max(1, Math.min(8, gens.length || 3));
    const results = await runLineage({ seed: c.seed, brain: c.brain, gens: n });
    if (results.length !== gens.length) {
      diffs.push({ seed: c.seed, brain: c.brain, gen: "-", field: "genCount", expected: gens.length, got: results.length });
    }
    const k = Math.min(gens.length, results.length);
    for (let i = 0; i < k; i++) {
      for (const f of FIELDS) {
        const expected = gens[i][f], got = results[i][f];
        if (expected !== got) {
          failed++;
          diffs.push({ seed: c.seed, brain: c.brain, gen: gens[i].gen, field: f, expected, got });
        } else passed++;
      }
    }
  }

  if (diffs.length) {
    console.log("[world-parity] MISMATCHES:");
    for (const d of diffs) {
      console.log(`  seed=${d.seed} brain=${d.brain} gen=${d.gen} ${d.field}: expected ${JSON.stringify(d.expected)} got ${JSON.stringify(d.got)}`);
    }
  } else {
    console.log(`[world-parity] ${cases.length} case(s): ${passed} field checks passed, 0 failed.`);
  }
  return { skipped: false, passed, failed };
}

// standalone entry point
const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  const r = await runParity();
  if (!r.skipped && r.failed > 0) process.exitCode = 1;
}
